# 版本号
[versions]
# ----- 核心组件 -----
appcompat = "1.6.1"
material = "1.8.0"
constraintLayout = "2.1.4"
recyclerview = "1.3.2"

ktx_core = "1.10.1"
ktx_coroutine = "1.8.1"
ktx_lifecycleRuntime = "2.5.1"
ktx_lifecycleViewModel = "2.5.1"

annotation = "1.9.1"
desugarLibs = "2.0.4"

compose-bom = "2023.06.01"
compose-activity = "1.6.1"
compose-compiler = "1.5.7"


# ----- 实用工具 -----
utilCodeX = "1.31.1"

freeReflection = "3.1.0"


# ----- 媒体技术 -----
glide-core = "4.16.0"

coil-core = "1.1.1"
coil-gif = "0.9.5"

media3 = "1.1.0"


# ----- 数据存储 -----
room = "2.5.1"

debugDB = "1.0.7"


# ----- 网络通讯 -----
okdownload-core = "1.0.7"


# ----- 工程架构 -----
kunminx_unpeekLiveData = "7.8.0"

hilt = "2.52"


# ----- 测试工具 -----
androidx_test_junit = "1.2.1"
androidx_test_espresso = "3.6.1"

jraska_livedata-test = "1.3.0"


# ----- Gradle插件 -----
plugin_agp = "7.4.2"
plugin_kotlin = "1.9.21"


# 组件
[libraries]
# ----- 核心组件 -----
# < Android 官方组件 >
# AppCompat
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
# Google Material Design
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
# Constraint Layout
constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
# RecyclerView
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }

# Android相关注解
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
# JVM8-11兼容模块
desugarLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugarLibs" }

# < Android Kotlin扩展 >
# 核心
ktx_core = { group = "androidx.core", name = "core-ktx", version.ref = "ktx_core" }
# 协程
ktx_coroutine = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "ktx_coroutine" }
# Lifecycle-Runtime
ktx_lifecycleRuntime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "ktx_lifecycleRuntime" }
# Lifecycle-ViewModel
ktx_lifecycleViewModel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "ktx_lifecycleViewModel" }

# < Jetpack Compose >
# BOM文件（其他组件的版本配置文件）
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
# 核心组件
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
# Material3支持
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
# Activity支持
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
# 调试工具
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
# 测试工具
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }


# ----- 实用工具 -----
# UtilCodeX
utilCodeX = { group = "com.blankj", name = "utilcodex", version.ref = "utilCodeX" }

# FreeReflection（解除Android 10及以上版本的隐藏接口反射限制）
freeReflection = { group = "com.github.tiann", name = "FreeReflection", version.ref = "freeReflection" }


# ----- 媒体技术 -----
# < Glide >
# 核心
glide-core = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide-core" }
# 注解处理器
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide-core" }

# < Coil >
# 核心
coil-core = { group = "io.coil-kt", name = "coil", version.ref = "coil-core" }
# GIF支持
coil-gif = { group = "io.coil-kt", name = "coil-gif", version.ref = "coil-gif" }

# < Jetpack Media3 >
# ExoPlayer核心
media3_exoplayer-core = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
# ExoPlayer-DASH支持
media3_exoplayer-dash = { group = "androidx.media3", name = "media3-exoplayer-dash", version.ref = "media3" }
# ExoPlayer-HLS支持
media3_exoplayer-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "media3" }
# ExoPlayer-SmoothStreaming支持
media3_exoplayer-smoothstreaming = { group = "androidx.media3", name = "media3-exoplayer-smoothstreaming", version.ref = "media3" }
# ExoPlayer-RTSP支持
media3_exoplayer-rtsp = { group = "androidx.media3", name = "media3-exoplayer-rtsp", version.ref = "media3" }
# ExoPlayer-MIDI支持
media3_exoplayer-midi = { group = "androidx.media3", name = "media3-exoplayer-midi", version.ref = "media3" }
# ExoPlayer-Interactive Media AD支持
media3_exoplayer-ima = { group = "androidx.media3", name = "media3-exoplayer-ima", version.ref = "media3" }
# UI组件（包括ExoPlayer的播放器控件）
media3_ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }


# ----- 数据存储 -----
# < Room >
# 核心
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
# 注解处理器
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
# Kotlin扩展
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
# 测试工具
room-test = { group = "androidx.room", name = "room-testing", version.ref = "room" }

# < 调试工具 >
# SQLite Web调试工具
debugDB = { group = "com.github.amitshekhariitbhu.Android-Debug-Database", name = "debug-db", version.ref = "debugDB" }


# ----- 网络通讯 -----
# < OkDownload >
# 核心
okdownload-core = { group = "com.liulishuo.okdownload", name = "okdownload", version.ref = "okdownload-core" }


# ----- 工程架构 -----
# UnPeekLiveData（被订阅时不会立刻回调当前值的LiveData实现，适用于事件分发等场景。）
kunminx_unpeekLiveData = { group = "com.kunminx.arch", name = "unpeek-livedata", version.ref = "kunminx_unpeekLiveData" }

# < Dagger >
# Dagger・Hilt・Android
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
# Dagger・Hilt・注解处理器
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }


# ----- 测试工具 -----
# < AndroidX Test >
# AndroidX Test JUnit扩展（提供AndroidJUnit4，方便与JUnit集成。）
androidx_test_junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx_test_junit" }
# AndroidX Test Espresso运行环境
androidx_test_espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx_test_espresso" }

# < Jraska LiveData 测试工具 >
# Jraska LiveData 测试工具(Java)
jraska_liveDataTest-java = { group = "com.jraska.livedata", name = "testing", version.ref = "jraska_livedata-test" }
# Jraska LiveData 测试工具(Kotlin)
jraska_liveDataTest-kotlin = { group = "com.jraska.livedata", name = "testing-ktx", version.ref = "jraska_livedata-test" }


# 编组
[bundles]
# ----- 核心组件 -----
# APP
# 核心组件
appBase = ["appcompat", "material", "constraintLayout"]
# 核心组件(Kotlin)
appBaseKT = ["appcompat", "material", "constraintLayout", "ktx_core", "ktx_coroutine", "ktx_lifecycleRuntime", "ktx_lifecycleViewModel"]

# Jetpack Compose
# 核心组件
compose-core = ["compose-ui", "compose-ui-graphics", "compose-material3", "compose-activity", "compose-ui-tooling", "compose-ui-tooling-preview"]
# 测试工具
compose-test = ["compose-ui-test-manifest", "compose-ui-test-junit4"]


# ----- 图像处理 -----
coil = ["coil-core", "coil-gif"]


# Gradle插件
[plugins]
application = { id = "com.android.application", version.ref = "plugin_agp" }
library = { id = "com.android.library", version.ref = "plugin_agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "plugin_kotlin" }
parcelize = { id = "kotlin-parcelize" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
