# 版本号
[versions]
# ----- 核心组件 -----
appcompat = "1.6.1"
material = "1.8.0"
constraintLayout = "2.1.4"

ktx_core = "1.10.1"
ktx_coroutine = "1.8.1"
ktx_lifecycleRuntime = "2.5.1"
ktx_lifecycleViewModel = "2.5.1"

desugarLibs = "2.0.4"

compose_bom = "2023.06.01"
compose_activity = "1.6.1"
compose_compiler = "1.5.7"


# ----- 实用工具 -----
utilCodeX = "1.31.1"


# ----- 图像处理 -----
glide_core = "4.16.0"

coil_core = "1.1.1"
coil_gif = "0.9.5"


# ----- 数据存储 -----
debugDB = "1.0.7"

room = "2.5.1"


# ----- 网络通讯 -----
okdownload_core = "1.0.7"


# ----- Gradle插件 -----
plugin_agp = "7.4.2"
plugin_kotlin = "1.9.21"


# 组件
[libraries]
# ----- 核心组件 -----
# < Android 官方组件 >
# AppCompat
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
# Constraint Layout
constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
# Google Material Design
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# JVM8-11兼容模块
desugarLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugarLibs" }

# < Android Kotlin扩展 >
# 核心
ktx_core = { group = "androidx.core", name = "core-ktx", version.ref = "ktx_core" }
# 协程
ktx_coroutine = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "ktx_coroutine" }
# Lifecycle-Runtime
ktx_lifecycleRuntime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "ktx_lifecycleRuntime" }
# Lifecycle-ViewModel
ktx_lifecycleViewModel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "ktx_lifecycleViewModel" }

# < Jetpack Compose >
# BOM文件（其他组件的版本配置文件）
compose_bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose_bom" }
# 核心组件
compose_ui = { group = "androidx.compose.ui", name = "ui" }
compose_ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
# Material3支持
compose_material3 = { group = "androidx.compose.material3", name = "material3" }
# Activity支持
compose_activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose_activity" }
# 调试工具
compose_ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose_ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
# 测试工具
compose_ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose_ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }


# ----- 实用工具 -----
# UtilCodeX
utilCodeX = { group = "com.blankj", name = "utilcodex", version.ref = "utilCodeX" }


# ----- 图像处理 -----
# < Glide >
# 核心
glide_core = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide_core" }
# 注解处理器
glide_compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide_core" }

# < Coil >
# 核心
coil_core = { group = "io.coil-kt", name = "coil", version.ref = "coil_core" }
# GIF支持
coil_gif = { group = "io.coil-kt", name = "coil-gif", version.ref = "coil_gif" }


# ----- 数据存储 -----
# < Room >
# 核心
room_runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
# 注解处理器
room_compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
# Kotlin扩展
room_ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
# 测试工具
room_test = { group = "androidx.room", name = "room-testing", version.ref = "room" }

# < 调试工具 >
# Web调试工具
debugDB = { group = "com.github.amitshekhariitbhu.Android-Debug-Database", name = "debug-db", version.ref = "debugDB" }


# ----- 网络通讯 -----
# < OkDownload >
# 核心
okdownload_core = { group = "com.liulishuo.okdownload", name = "okdownload", version.ref = "okdownload_core" }


# 编组
[bundles]
# ----- 核心组件 -----
# APP
# 核心组件
appBase = ["appcompat", "material", "constraintLayout"]
# 核心组件(Kotlin)
appBaseKT = ["appcompat", "material", "constraintLayout", "ktx_core", "ktx_coroutine", "ktx_lifecycleRuntime", "ktx_lifecycleViewModel"]

# Jetpack Compose
# 核心组件
compose_core = ["compose_ui", "compose_ui-graphics", "compose_material3", "compose_activity", "compose_ui-tooling", "compose_ui-tooling-preview"]
# 测试工具
compose_test = ["compose_ui-test-manifest", "compose_ui-test-junit4"]


# ----- 图像处理 -----
coil = ["coil_core", "coil_gif"]


# Gradle插件
[plugins]
application = { id = "com.android.application", version.ref = "plugin_agp" }
library = { id = "com.android.library", version.ref = "plugin_agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "plugin_kotlin" }
